name: Pipeline

on: [push]

env:
  POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
  POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn typecheck
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn audit
  test:
    runs-on: ubuntu-latest
    container: node:lts
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: psql --host=${{ env.POSTGRES_HOST }} --port=${{ env.POSTGRES_PORT }} --username=postgres --command="CREATE USER ${{ env.POSTGRES_USERNAME }} PASSWORD '${{ env.POSTGRES_PASSWORD }}'" --command="\du"
      - run: psql --host=${{ env.POSTGRES_HOST }} --port=${{ env.POSTGRES_PORT }} --username=postgres --command="CREATE DATABASE ${{ env.POSTGRES_DATABASE }} OWNER ${{ env.POSTGRES_USERNAME }}"
      - env:
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USERNAME }}:${{ secrets.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ secrets.POSTGRES_DATABASE }}
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" > .env
          cat .env
      - run: yarn
      - run: yarn test
  build:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, audit, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn build
